### ISSUE TITLE
How In The Actual F* Do You Use This

### ISSUE THREAD

**Issue by iHaxtedU** [Arisstath/AxonObfuscator#1]
Title says it all, LOL

**Comment by Arisstath** [comment]
Take a look here https://github.com/Arisstath/AxonObfuscator/blob/e665e73a0e4d6e2adbb491e76aac1a8ea4c9e850/src/main/java/icu/axon/obfuscator/Obfuscator.java#L161

**Comment by iHaxtedU** [comment]
> Take a look here
> 
> [AxonObfuscator/src/main/java/icu/axon/obfuscator/Obfuscator.java](https://github.com/Arisstath/AxonObfuscator/blob/e665e73a0e4d6e2adbb491e76aac1a8ea4c9e850/src/main/java/icu/axon/obfuscator/Obfuscator.java#L161)
> 
> Line 161 in [e665e73](/Arisstath/AxonObfuscator/commit/e665e73a0e4d6e2adbb491e76aac1a8ea4c9e850)
> 
>  post("/obfuscate", (req, res) -> {

Im very new to this, sorry to ask but how would you compile or run something like this, cmd or ???

**Comment by LoganDark** [comment]
https://github.com/Arisstath/AxonObfuscator/issues/2#issuecomment-605410057
